quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://customers.db.external.acme.org:5432/customersdb
%prod.quarkus.datasource.jdbc.max-size=8
%prod.quarkus.datasource.jdbc.min-size=2

%prod.quarkus.http.port=8080
quarkus.openshift.route.expose=true
quarkus.helm.repository.deployment-target=openshift

quarkus.swagger-ui.always-include=true
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, PUT, POST
